# Necessary imports
import sys
import gradio as gr
import spaces

# Local imports
from src.config import device, model_name, sampling, enable_thinking
from src.minicpm.model import load_model
from src.logger import logging
from src.exception import CustomExceptionHandling


# Model
model = load_model(model_name, device)


@spaces.GPU(duration=120)
def describe_image(
    image: str,
    question: str,
    temperature: float,
    top_p: float,
    top_k: int,
    max_new_tokens: int,
) -> str:
    """
    Generates an answer to a given question based on the provided image and question.

    Args:
        - image (str): The path to the image file.
        - question (str): The question text.
        - temperature (float): The temperature parameter for the model.
        - top_p (float): The top_p parameter for the model.
        - top_k (int): The top_k parameter for the model.
        - max_new_tokens (int): The max tokens to be generated by the model.

    Returns:
        str: The generated answer to the question.
    """
    try:
        # Check if image or question is None
        if not image or not question:
            raise gr.Error("Please provide an image and a question.")

        # Message format for the model
        msgs = [{"role": "user", "content": [image, question]}]

        # Generate the answer
        answer = model.chat(
            msgs=msgs,
            use_tts_template=False,
            enable_thinking=enable_thinking,
            do_sample=sampling,
            top_p=top_p,
            top_k=top_k,
            temperature=temperature,
            max_new_tokens=max_new_tokens,
        )

        # Log the successful generation of the answer
        logging.info("Answer generated successfully.")

        # Return the answer
        return answer

    # Handle exceptions that may occur during answer generation
    except Exception as e:
        # Custom exception handling
        raise CustomExceptionHandling(e, sys) from e
